In [1]:
import pandas as pd
import numpy as np

In [2]:
people=pd.read_csv("../data/raw/resumes/01_people.csv")
abilities=pd.read_csv("../data/raw/resumes/02_abilities.csv")
education=pd.read_csv("../data/raw/resumes/03_education.csv")
experience=pd.read_csv("../data/raw/resumes/04_experience.csv")
person_skills=pd.read_csv("../data/raw/resumes/05_person_skills.csv")
skills=pd.read_csv("../data/raw/resumes/06_skills.csv")

In [3]:
#Check dataset dimensions
print("People:", people.shape)
print("Abilities:", abilities.shape)
print("Education:", education.shape)
print("Experience:", experience.shape)
print("Person Skills:", person_skills.shape)
print("Skills:", skills.shape)

People: (54933, 5)
Abilities: (1219473, 2)
Education: (75999, 5)
Experience: (265404, 6)
Person Skills: (2483376, 2)
Skills: (226760, 1)

In [4]:
print("\nPeople: ",people.columns)
print("\nAbilities: ",abilities.columns)
print("\nEducation: ",education.columns)
print("\nExperience: ",experience.columns)
print("\nPerson Skills: ",person_skills.columns)
print("\nSkills: ",skills.columns)

People:  Index(['person_id', 'name', 'email', 'phone', 'linkedin'], dtype='object')

Abilities:  Index(['person_id', 'ability'], dtype='object')

Education:  Index(['person_id', 'institution', 'program', 'start_date', 'location'], dtype='object')

Experience:  Index(['person_id', 'title', 'firm', 'start_date', 'end_date', 'location'], dtype='object')

Person Skills:  Index(['person_id', 'skill'], dtype='object')

Skills:  Index(['skill'], dtype='object')

In [5]:
print("People:", people["person_id"].nunique())
print("Education:", education["person_id"].nunique())
print("Experience:", experience["person_id"].nunique())
print("Abilities:", abilities["person_id"].nunique())
print("Person Skills:", person_skills["person_id"].nunique())

People: 54933
Education: 48075
Experience: 54933
Abilities: 54930
Person Skills: 54858

In [6]:
people[people["person_id"]==1]

   person_id                    name email phone linkedin
0          1  Database Administrator   NaN   NaN      NaN

In [7]:
education[education["person_id"]==1]

   person_id           institution              program start_date location
0          1  Lead City University  Bachelor of Science    07/2013      NaN

In [8]:
experience[experience["person_id"]==1]

,person_id,title,firm,start_date,end_date,location
0,1,Database Administrator,Family Private Care LLC,04/2017,Present,"Roswell, GA"
1,1,Database Administrator,Incomm,01/2014,02/2017,"Alpharetta, GA"

In [9]:
abilities[abilities["person_id"]==1]

    person_id                              ability
0           1     Installation and Building Server
1           1                      Running Backups
2           1      Recovering and Restoring Models
3           1        Support various MS SQL Server
4           1              MS SQL Server 2005/2008
5           1         environments from SQL Server
6           1                  /2008R2R2/2012/2014
7           1       2005 thru SQL Server 2008r2 as
8           1             administration including
9           1      well as with SQL Server 2012 on
10          1         installation, configuration,
11          1         upgrades, capacity planning,
12          1       performance tuning, backup and
13          1                            recovery.
14          1     Familiar with virtualization and
15          1          managing SQL databases in a
16          1                 virtual environment.
17          1        Management of users including
18          1        creation/alteration, grant of
19          1      system/DB roles and permissions
20          1         on various database objects.
21          1      Design and implement SQL Server
22          1  201, databases for mission-critical
23          1            2005, SQL Server 2008 R2,
24          1                            business.
25          1      Environment transition planning
26          1           (development, test, stage,
27          1                         production).
28          1           Perform routine backup and
29          1     recovery testing and documenting
30          1                  recovery scenarios.
31          1                 Use SQL Profiler for
32          1     troubleshooting, monitoring, and
33          1       optimization of SQL Server and
34          1                            SQL code.
35          1            Manage the production and
36          1      development databases including
37          1         performance tuning, capacity
38          1     planning, SQL Server clustering,
39          1     database security configuration,
40          1             and database continuity.
41          1                Excellent analytical,
42          1    communication skills, work ethics
43          1        and ability to work in a team
44          1              environment with strong
45          1      determination and commitment to
46          1                    the deliverables.
47          1   Highly motivated self-starter with
48          1   the ability to work independently.

In [10]:
person_skills[person_skills["person_id"]==1]

    person_id                    skill
0           1  Database administration
1           1                 Database
2           1            Ms sql server
3           1       Ms sql server 2005
4           1               Sql server
5           1          Sql server 2005
6           1          Sql server 2008
7           1       Sql server 2008 r2
8           1          Sql server 2012
9           1                      Sql
10          1              Sql queries
11          1        Stored procedures
12          1               Clustering
13          1                  Backups
14          1                    T-sql
15          1           Virtualization
16          1                       R2
17          1              Maintenance
18          1          Problem solving
19          1                 Shipping
20          1  Database administration
21          1                 Database
22          1            Ms sql server
23          1       Ms sql server 2005
24          1               Sql server
25          1          Sql server 2005
26          1          Sql server 2008
27          1       Sql server 2008 r2
28          1          Sql server 2012
29          1                      Sql
30          1              Sql queries
31          1        Stored procedures
32          1               Clustering
33          1                  Backups
34          1                    T-sql
35          1           Virtualization
36          1                       R2
37          1              Maintenance
38          1          Problem solving
39          1                 Shipping

In [11]:
person_skills[person_skills["person_id"] == 1]["skill"].nunique()

20

In [12]:
experience[experience["person_id"] == 1].shape

(2, 6)

In [13]:
education[education["person_id"] == 1].shape

(1, 5)

In [14]:
abilities[abilities["person_id"] == 1].shape

(49, 2)

In [15]:
person_skills[person_skills["person_id"] == 1].shape

(40, 2)

In [16]:
person_skills.duplicated().sum()

np.int64(587511)

In [17]:
person_skills = person_skills.drop_duplicates()

In [18]:
person_skills

         person_id                                              skill
0                1                            Database administration
1                1                                           Database
2                1                                      Ms sql server
3                1                                 Ms sql server 2005
4                1                                         Sql server
...            ...                                                ...
2483370      54933      Developing Controllers using django framework
2483371      54933    Designed APIs to retrieve the list of new tasks
2483372      54933                 Creating a Data models for the app
2483373      54933  Developing the static pages using Bootstrap an...
2483375      54933       Creating database schema for sqlite Database

[1895865 rows x 2 columns]

In [19]:
person_skills.duplicated().sum()

np.int64(0)

In [20]:
person_skills.shape

(1895865, 2)

In [21]:
grouped = person_skills.groupby("person_id")

In [22]:
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [23]:
grouped.get_group(1)

    person_id                    skill
0           1  Database administration
1           1                 Database
2           1            Ms sql server
3           1       Ms sql server 2005
4           1               Sql server
5           1          Sql server 2005
6           1          Sql server 2008
7           1       Sql server 2008 r2
8           1          Sql server 2012
9           1                      Sql
10          1              Sql queries
11          1        Stored procedures
12          1               Clustering
13          1                  Backups
14          1                    T-sql
15          1           Virtualization
16          1                       R2
17          1              Maintenance
18          1          Problem solving
19          1                 Shipping

In [24]:
skills_per_person = (
    person_skills
    .groupby("person_id")["skill"]
    .apply(lambda skills: ", ".join(skills))
    .reset_index()
)

TypeError: sequence item 12: expected str instance, float found

In [ ]:
person_skills["skill"].isna().sum()

np.int64(6)

In [ ]:
person_skills = person_skills.dropna(subset=["skill"])

In [ ]:
person_skills["skill"].isna().sum()

np.int64(0)

In [ ]:
# Transform multiple skill records into a single row per person
skills_per_person = (
    person_skills
    .groupby("person_id")["skill"]
    .apply(lambda skills: ", ".join(pd.unique(skills)))
    .reset_index()
)

In [ ]:
# Preview the aggregated skills dataset
skills_per_person.head()

,person_id,skill
0,1,"Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping"
1,2,"sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel"
2,3,"DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)"
3,4,"Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS"
4,5,"Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD"

In [ ]:
skills_per_person.shape

(54858, 2)

In [ ]:
pd.set_option("display.max_colwidth", None)
skills_per_person.head()

,person_id,skill
0,1,"Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping"
1,2,"sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel"
2,3,"DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)"
3,4,"Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS"
4,5,"Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD"

In [ ]:
print(skills_per_person.iloc[0]["skill"])

Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping

In [ ]:
skills_per_person = (
    person_skills
    .groupby("person_id")["skill"]
    .apply(lambda skills: ", ".join(pd.unique(skills)))
    .reset_index()
)

In [ ]:
experience[experience["person_id"] == 1]

,person_id,title,firm,start_date,end_date,location
0,1,Database Administrator,Family Private Care LLC,04/2017,Present,"Roswell, GA"
1,1,Database Administrator,Incomm,01/2014,02/2017,"Alpharetta, GA"

In [ ]:
experience["experience_text"] = (
    experience["title"]
    + " at "
    + experience["firm"]
    + " ("
    + experience["start_date"]
    + " - "
    + experience["end_date"]
    + ")"
)

In [ ]:
experience["experience_text"]

0             Database Administrator at Family Private Care LLC (04/2017 - Present)
1                              Database Administrator at Incomm (01/2014 - 02/2017)
2           Database Administrator at Intercontinental Registry (12/2008 - 08/2011)
3                    Oracle Database Administrator at Cognizant (06/2016 - Present)
4                    Oracle Database Administrator at Convergys (06/2014 - 06/2016)
                                            ...
265399        Python Developer at Hexaware Technologies Limited (07/2010 - 10/2011)
265400            Software Developer at Vision InfoTech Pvt Ltd (03/2009 - 06/2010)
265401                                 MetroBikes at MetroBikes (09/2018 - Present)
265402    Python/Flask Developer at TechJini Solutions Pvt. Ltd (04/2017 - 07/2018)
265403          Python Developer at TechJini Solutions Pvt. Ltd (12/2015 - 02/2017)
Name: experience_text, Length: 265404, dtype: object

In [ ]:
experience[["person_id", "experience_text"]].head()

,person_id,experience_text
0,1,Database Administrator at Family Private Care LLC (04/2017 - Present)
1,1,Database Administrator at Incomm (01/2014 - 02/2017)
2,2,Database Administrator at Intercontinental Registry (12/2008 - 08/2011)
3,3,Oracle Database Administrator at Cognizant (06/2016 - Present)
4,3,Oracle Database Administrator at Convergys (06/2014 - 06/2016)

In [ ]:

experience["experience_text"].isna().sum()

np.int64(6738)

In [ ]:
experience[experience["experience_text"].isna()].head(10)

,person_id,title,firm,start_date,end_date,location,experience_text
44,16,SQL DBA/ Database Administrator,NaN,2014/01,2016/12,NaN,NaN
45,16,SQL DBA/ Database Administrator,NaN,2003/01,2008/12,NaN,NaN
202,64,Independent SQL Consultant,NaN,01/17,06/18,NaN,NaN
230,71,Oracle Database Administrator - Business Solutions,Ntt Data,01/2019,NaN,Hyd,NaN
273,82,Payroll Specialist,The Whole Person,NaN,NaN,"Kansas City, MO",NaN
274,82,Release Specialist,James B Nutter & Company,NaN,NaN,"Kansas City, MO",NaN
275,82,Office Manager / Designer,Extreme Signs,NaN,NaN,"Independence, Missouri",NaN
394,117,Lead Technology Specialist,City of Phoenix,NaN,NaN,NaN,NaN
395,117,Manager Database Systems,Promark One/IDRC,NaN,NaN,"Scottsdale, AZ",NaN
396,117,Senior Database Administrator,Choice Hotels International,NaN,NaN,"Phoenix, AZ",NaN

In [ ]:
experience["firm"] = experience["firm"].fillna("Unknown Company")
experience["start_date"] = experience["start_date"].fillna("Unknown Start")
experience["end_date"] = experience["end_date"].fillna("Present")
experience["title"] = experience["title"].fillna("Unknown Role")

In [ ]:
experience["experience_text"] = (
    experience["title"]
    + " at "
    + experience["firm"]
    + " ("
    + experience["start_date"]
    + " - "
    + experience["end_date"]
    + ")"
)

In [ ]:
experience["experience_text"].isna().sum()

np.int64(0)

In [ ]:
experience_per_person=experience.groupby("person_id")["experience_text"].apply(lambda experiences: "; ".join(experiences)).reset_index()

In [ ]:
experience_per_person.head(10)

,person_id,experience_text
0,1,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017)
1,2,Database Administrator at Intercontinental Registry (12/2008 - 08/2011)
2,3,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016)
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)"
4,5,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013)
5,6,Oracle Database Administrator at SUNTRUST BANK (02/2015 - Present); Oracle Database Administrator at ESTES-EXPRESS (03/2013 - 02/2015); Field Service Representative / Technician at ROCHE DIAGNOSTICS FOR ADECCO TECHNICAL (10/2009 - 03/2013)
6,7,Oracle Database Administrator at Caresource (06/17 - Present); Oracle Database Administrator at Anthem (04/16 - 06/17); Production Support Database Administrator at PNC Bank (03/13 - 04/16)
7,8,"Lead Database Administrator/Developer at Department of Housing and Urban Development (2017 - Present); Production Support Database Administrator at Citi Group (2016 - 2017); Oracle Database Administrator at Citi Group (2014 - 2015); Database Administrator at University of Maryland, University College (2012 - 2014)"
8,9,"Database Administrator / Database Developer at Dominion Diagnostics, LLC (04/2019 - Present); Database Administrator at Teknor Apex Company (12/2016 - 03/2019); Senior Database Specialist at CVS Health (09/2015 - 11/2016); Database Specialist at CVS Health (05/2014 - 09/2015); Technical Support Consultant at CVS Health (06/2013 - 05/2014); Consumer Relations Representative at Kaz USA Inc (06/2012 - 06/2013)"
9,10,Oracle Database Administrator at Uber Technologies Inc (11/2017 - Present); Database Administrator / Developer at SYSCO (03/2015 - 10/2017); NFI Junior DBA at NFI (03/2012 - 01/2015)

In [ ]:
education.isna().sum()

person_id          0
institution     1569
program         7761
start_date     21129
location       23256
dtype: int64

In [ ]:
education["institution"] = education["institution"].fillna("Unknown Institution")
education["program"] = education["program"].fillna("Unknown Program")
education["start_date"] = education["start_date"].fillna("Unknown Start")
education["location"] = education["location"].fillna("Unknown Location")

In [ ]:
education.head(10)

,person_id,institution,program,start_date,location
0,1,Lead City University,Bachelor of Science,07/2013,Unknown Location
1,2,lagos state university,bsc in computer science,Unknown Start,"Lagos, GU"
2,3,"JNTU - Kakinada, Andhra Pradesh",Master of Computer Applications in Science and technology,2013,"Kakinada, Andhra Pradesh"
3,4,University of Informatics,Bachelor in Computer Science,06/07,June 2007
4,5,Virginia Commomwealth University,Unknown Program,08/2013,"Richmond, VA"
5,6,"School of Professional and Graduate Studies/Technical Courses, BAKER UNIVERSITY",Unknown Program,Unknown Start,"Overland Park, KS"
6,6,UNIVERSITY OF ALASKA,General/Business/Science Courses,Unknown Start,"Anchorage, AK"
7,7,University Of Yaounde,Biochemistry,04/08,Yaounde
8,8,Bowie State University,Bachelor's Degree in BiologyChem / Computer Science,Unknown Start,Unknown Location
9,9,Bridgewater State University,Management - Information Systems,Unknown Start,Present

In [ ]:
education["education_info"]= (
    education["program"]    + " from "
    + education["institution"]
    + ", "
    + education["location"]
    + " ("
    + education["start_date"]
    + ")"
)

In [ ]:
education["education_info"].head(10)

0                                                                  Bachelor of Science from Lead City University, Unknown Location (07/2013)
1                                                             bsc in computer science from lagos state university, Lagos, GU (Unknown Start)
2            Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)
3                                                             Bachelor in Computer Science from University of Informatics, June 2007 (06/07)
4                                                              Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)
5    Unknown Program from School of Professional and Graduate Studies/Technical Courses, BAKER UNIVERSITY, Overland Park, KS (Unknown Start)
6                                                  General/Business/Science Courses from UNIVERSITY OF ALASKA, Anchorage, AK (Unknown Start)
7                                                                                   Biochemistry from University Of Yaounde, Yaounde (04/08)
8                          Bachelor's Degree in BiologyChem / Computer Science from Bowie State University, Unknown Location (Unknown Start)
9                                                Management - Information Systems from Bridgewater State University, Present (Unknown Start)
Name: education_info, dtype: object

In [ ]:
education["person_id"].duplicated().sum()

np.int64(27924)

In [ ]:
education["person_id"].shape

(75999,)

In [ ]:
education_grouped=education.groupby("person_id")["education_info"].apply(lambda ed_info:"; ".join(ed_info)).reset_index()

In [ ]:
education_grouped.head(20)

,person_id,education_info
0,1,"Bachelor of Science from Lead City University, Unknown Location (07/2013)"
1,2,"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)"
2,3,"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)"
3,4,"Bachelor in Computer Science from University of Informatics, June 2007 (06/07)"
4,5,"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)"
5,6,"Unknown Program from School of Professional and Graduate Studies/Technical Courses, BAKER UNIVERSITY, Overland Park, KS (Unknown Start); General/Business/Science Courses from UNIVERSITY OF ALASKA, Anchorage, AK (Unknown Start)"
6,7,"Biochemistry from University Of Yaounde, Yaounde (04/08)"
7,8,"Bachelor's Degree in BiologyChem / Computer Science from Bowie State University, Unknown Location (Unknown Start)"
8,9,"Management - Information Systems from Bridgewater State University, Present (Unknown Start); Computer Science/Information Systems from Bristol Community College, Unknown Location (Unknown Start); Computer Science/Information Systems from University of Massachusetts - Dartmouth, Dartmouth, MA (Unknown Start)"
9,10,"Information Technology from University of Maryland-University College, Adelphi, MD (Unknown Start)"
10,11,"BA Political Science from George Washington University, Washington, DC (2010)"
11,12,"Associate's degree from University of Maryland, Unknown Location (Unknown Start)"
12,13,"Bachelor's Degree from University of Yaoundé II, Unknown Location (Unknown Start)"
13,14,"B.A. in Computer Science from The University of Iowa, Iowa City, IA (05/16)"
14,15,"Bachelor's in Management in Finance from Sufia Institute of Science & Technology, Unknown Location (Unknown Start)"
15,16,"Unknown Program from Unknown Institution, Unknown Location (Unknown Start)"
16,17,"Master's in science from University of Trento, Italy (Unknown Start); Master's in Science from Addis Ababa University, Ethiopia (Unknown Start)"
17,18,"Bachelor of Business Administration in Accounting from Middle Tennessee State University, Murfreesboro, TN (05/11)"
18,19,"Bachelor of Science from Radford University, Radford, VA (08/09)"
19,20,"Computer Science from Stevens Institute of Technology, Hoboken, NJ (2010)"

In [ ]:
education_grouped.shape

(48075, 2)

In [ ]:
grouped.get_group(1)

    person_id                    skill
0           1  Database administration
1           1                 Database
2           1            Ms sql server
3           1       Ms sql server 2005
4           1               Sql server
5           1          Sql server 2005
6           1          Sql server 2008
7           1       Sql server 2008 r2
8           1          Sql server 2012
9           1                      Sql
10          1              Sql queries
11          1        Stored procedures
12          1               Clustering
13          1                  Backups
14          1                    T-sql
15          1           Virtualization
16          1                       R2
17          1              Maintenance
18          1          Problem solving
19          1                 Shipping

In [ ]:
abilities.head()

   person_id                           ability
0          1  Installation and Building Server
1          1                   Running Backups
2          1   Recovering and Restoring Models
3          1     Support various MS SQL Server
4          1           MS SQL Server 2005/2008

In [ ]:
abilities.shape

(1219473, 2)

In [ ]:
abilities.isna().sum()

person_id    0
ability      0
dtype: int64

In [ ]:
abilities_grouped = (
    abilities
    .groupby("person_id")["ability"]
    .apply(lambda abilities: "; ".join(abilities))
    .reset_index()
)

In [ ]:
abilities_grouped.shape

(54930, 2)

In [ ]:
abilities_grouped["person_id"].nunique()

54930

In [ ]:
abilities_grouped.head()

,person_id,ability
0,1,"Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently."
1,2,database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements
2,3,"Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures"
3,4,"SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office"
4,5,Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication

In [ ]:
skills_per_person.shape

(54858, 2)

In [ ]:
experience_per_person.shape

(54933, 2)

In [ ]:
education_grouped.shape

(48075, 2)

In [ ]:
abilities_grouped.shape

(54930, 2)

In [ ]:
skills_per_person.columns

Index(['person_id', 'skill'], dtype='object')

In [ ]:
experience_per_person.columns

Index(['person_id', 'experience_text'], dtype='object')

In [ ]:
education_grouped.columns

Index(['person_id', 'education_info'], dtype='object')

In [ ]:
abilities_grouped.columns

Index(['person_id', 'ability'], dtype='object')

In [ ]:
# EDA and feature engineering Summary

# experience_per_person : (54933, 2)
# education_grouped     : (48075, 2)
# skills_per_person     : (54858, 2)
# abilities_grouped     : (54930, 2)

In [ ]:
master_df = people.copy()
master_df

,person_id,name,email,phone,linkedin
0,1,Database Administrator,NaN,NaN,NaN
1,2,Database Administrator,NaN,NaN,NaN
2,3,Oracle Database Administrator,NaN,NaN,NaN
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN
...,...,...,...,...,...
54928,54929,Lead Python Developer,NaN,NaN,NaN
54929,54930,Full Stack Python Developer,NaN,NaN,NaN
54930,54931,Eli Lilly,NaN,NaN,NaN
54931,54932,Python Developer,NaN,NaN,NaN
54932,54933,Job Seeker,NaN,NaN,NaN

In [ ]:
master_df = master_df.merge(
    experience_per_person,
    on="person_id",
    how="left"
)

In [ ]:
master_df

,person_id,name,email,phone,linkedin,experience_text
0,1,Database Administrator,NaN,NaN,NaN,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017)
1,2,Database Administrator,NaN,NaN,NaN,Database Administrator at Intercontinental Registry (12/2008 - 08/2011)
2,3,Oracle Database Administrator,NaN,NaN,NaN,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016)
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)"
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013)
...,...,...,...,...,...,...
54928,54929,Lead Python Developer,NaN,NaN,NaN,Lead Python Developer at People's United Bank (08/2016 - Present); Lead Python Developer at Entrust (10/2015 - 07/2016); Sr. Python Developer at Guide One Insurance (03/2014 - 09/2015); Sr. Python Developer at Examity (12/2012 - 02/2014); Python Developer at ANZ Bank (02/2011 - 09/2012); Web developer at Rofous (11/2007 - 01/2011)
54929,54930,Full Stack Python Developer,NaN,NaN,NaN,"Full Stack Python Developer at Fresenius Medical Care, MA (01/2016 - Present); Sr. Python Developer at Hughes Networks (03/2014 - 01/2016); Python Developer at Manheim Inc (05/2013 - 02/2014); Python Developer at DTCC (11/2012 - 05/2013); Java/ Python Developer at RBS India (01/2011 - 10/2012); Java Developer at Neon Infotech PVT LTD (08/2009 - 12/2010)"
54930,54931,Eli Lilly,NaN,NaN,NaN,Sr. Python Developer at Eli Lilly (08/2017 - Present); Sr. Python Developer at Comcast (01/2016 - 07/2017); Python Developer at Core logic (08/2013 - 12/2015); Python Developer at Concentrix Insurance Solutions (11/2011 - 07/2013); Java Developer at Solvent Software Solutions PVT LTD (09/2010 - 10/2011); Python Developer at Nova IT Solutions (07/2009 - 08/2010)
54931,54932,Python Developer,NaN,NaN,NaN,Python Developer at Intuit (08/2015 - Present); Python Developer at GE Energy (06/2014 - 07/2015); Python Developer at Safeway Inc (04/2013 - 05/2014); Python Developer at Intralinks Holdings Inc (11/2011 - 03/2013); Python Developer at Hexaware Technologies Limited (07/2010 - 10/2011); Software Developer at Vision InfoTech Pvt Ltd (03/2009 - 06/2010)
54932,54933,Job Seeker,NaN,NaN,NaN,MetroBikes at MetroBikes (09/2018 - Present); Python/Flask Developer at TechJini Solutions Pvt. Ltd (04/2017 - 07/2018); Python Developer at TechJini Solutions Pvt. Ltd (12/2015 - 02/2017)

In [ ]:
master_df = master_df.merge(
    education_grouped,
    on="person_id",
    how="left"
)
master_df.head()

,person_id,name,email,phone,linkedin,experience_text,education_info
0,1,Database Administrator,NaN,NaN,NaN,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017),"Bachelor of Science from Lead City University, Unknown Location (07/2013)"
1,2,Database Administrator,NaN,NaN,NaN,Database Administrator at Intercontinental Registry (12/2008 - 08/2011),"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)"
2,3,Oracle Database Administrator,NaN,NaN,NaN,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016),"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)","Bachelor in Computer Science from University of Informatics, June 2007 (06/07)"
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013),"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)"
...,...,...,...,...,...,...,...
54928,54929,Lead Python Developer,NaN,NaN,NaN,Lead Python Developer at People's United Bank (08/2016 - Present); Lead Python Developer at Entrust (10/2015 - 07/2016); Sr. Python Developer at Guide One Insurance (03/2014 - 09/2015); Sr. Python Developer at Examity (12/2012 - 02/2014); Python Developer at ANZ Bank (02/2011 - 09/2012); Web developer at Rofous (11/2007 - 01/2011),NaN
54929,54930,Full Stack Python Developer,NaN,NaN,NaN,"Full Stack Python Developer at Fresenius Medical Care, MA (01/2016 - Present); Sr. Python Developer at Hughes Networks (03/2014 - 01/2016); Python Developer at Manheim Inc (05/2013 - 02/2014); Python Developer at DTCC (11/2012 - 05/2013); Java/ Python Developer at RBS India (01/2011 - 10/2012); Java Developer at Neon Infotech PVT LTD (08/2009 - 12/2010)",NaN
54930,54931,Eli Lilly,NaN,NaN,NaN,Sr. Python Developer at Eli Lilly (08/2017 - Present); Sr. Python Developer at Comcast (01/2016 - 07/2017); Python Developer at Core logic (08/2013 - 12/2015); Python Developer at Concentrix Insurance Solutions (11/2011 - 07/2013); Java Developer at Solvent Software Solutions PVT LTD (09/2010 - 10/2011); Python Developer at Nova IT Solutions (07/2009 - 08/2010),NaN
54931,54932,Python Developer,NaN,NaN,NaN,Python Developer at Intuit (08/2015 - Present); Python Developer at GE Energy (06/2014 - 07/2015); Python Developer at Safeway Inc (04/2013 - 05/2014); Python Developer at Intralinks Holdings Inc (11/2011 - 03/2013); Python Developer at Hexaware Technologies Limited (07/2010 - 10/2011); Software Developer at Vision InfoTech Pvt Ltd (03/2009 - 06/2010),NaN
54932,54933,Job Seeker,NaN,NaN,NaN,MetroBikes at MetroBikes (09/2018 - Present); Python/Flask Developer at TechJini Solutions Pvt. Ltd (04/2017 - 07/2018); Python Developer at TechJini Solutions Pvt. Ltd (12/2015 - 02/2017),NaN

In [ ]:
master_df = master_df.merge(
    skills_per_person,
    on="person_id",
    how="left"
)
master_df.head()

,person_id,name,email,phone,linkedin,experience_text,education_info,skill
0,1,Database Administrator,NaN,NaN,NaN,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017),"Bachelor of Science from Lead City University, Unknown Location (07/2013)","Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping"
1,2,Database Administrator,NaN,NaN,NaN,Database Administrator at Intercontinental Registry (12/2008 - 08/2011),"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)","sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel"
2,3,Oracle Database Administrator,NaN,NaN,NaN,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016),"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)","DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)","Bachelor in Computer Science from University of Informatics, June 2007 (06/07)","Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS"
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013),"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)","Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD"
...,...,...,...,...,...,...,...,...
54928,54929,Lead Python Developer,NaN,NaN,NaN,Lead Python Developer at People's United Bank (08/2016 - Present); Lead Python Developer at Entrust (10/2015 - 07/2016); Sr. Python Developer at Guide One Insurance (03/2014 - 09/2015); Sr. Python Developer at Examity (12/2012 - 02/2014); Python Developer at ANZ Bank (02/2011 - 09/2012); Web developer at Rofous (11/2007 - 01/2011),NaN,"Django, Angular JS, JavaScript, JQuery, Node.js, Python, Object Oriented Programming, Linux, JSON, REST, AWS, Ansible, MySQL, Oracle, PostgreSQL, SQLite3, C++, STL, BOOST, XML, XPath, XSLT, IBM MQ, Perl, Python Scripting, Apache2, Nginx, AJAX, Object Oriented Design, SDLC, Rational Rose, UML, PEP-8, PIP, SQL, MongoDB, STLC, Agile, Waterfall, Jenkins, Spark, Git, SVN, CAN, LIN, MOST, Sqoop, Hadoop, Flask, HTML5, CSS3, Matplotlib, Regular Expressions, Bootstrap, Natural Language Processing, Celery, RabbitMQ, VMWare, SOAP, Puppet, Elasticsearch, HTML, CSS, Numpy, Robot, GitHub, Bitbucket, Redis, Windows, Bash, AMQP, CRUD, Cassandra, JSF, Spring, Psutil, Sqlite3, Beautiful Soup, Vugen, SoapUI, PHP, PL/SQL, MS SQL Server, jQuery"
54929,54930,Full Stack Python Developer,NaN,NaN,NaN,"Full Stack Python Developer at Fresenius Medical Care, MA (01/2016 - Present); Sr. Python Developer at Hughes Networks (03/2014 - 01/2016); Python Developer at Manheim Inc (05/2013 - 02/2014); Python Developer at DTCC (11/2012 - 05/2013); Java/ Python Developer at RBS India (01/2011 - 10/2012); Java Developer at Neon Infotech PVT LTD (08/2009 - 12/2010)",NaN,"Python, Django, AWS, AngularJS, Bootstrap, JavaScript, jQuery, JSON, HTML5, CSS3, MySQL, Linux, Ajax, Git, REST, XML, CSS, HTML, NodeJS, MongoDB, Cassandra, NumPy, Scipy, Jenkins, Ansible, Docker, AJAX, Backbone.js, D3.js, Java, JBoss, Node.js, Perforce, JIRA, J2EE, JSF, WebSphere, JPA, DHTML, JSP, Servlets, SQL, PL/SQL"
54930,54931,Eli Lilly,NaN,NaN,NaN,Sr. Python Developer at Eli Lilly (08/2017 - Present); Sr. Python Developer at Comcast (01/2016 - 07/2017); Python Developer at Core logic (08/2013 - 12/2015); Python Developer at Concentrix Insurance Solutions (11/2011 - 07/2013); Java Developer at Solvent Software Solutions PVT LTD (09/2010 - 10/2011); Python Developer at Nova IT Solutions (07/2009 - 08/2010),NaN,"Python 2.7, HTML5, CSS3, AJAX, JSON, JQuery, Active Records, XML, SOAP, SOA, WSDL, Spring MVC, DTDs, XSD, Python APIs, Scala, Shell, Groovy, Perl, SQL, Shell Scripting, Jenkins, GIT, Heroku, Bugzilla, C++, Java, MS SQL, Visual Basic, Linux, Eclipse, JavaScript, JASPER, PL/SQL, Oracle 9i, HTML5/CSS, Apache, Python, HTML, CSS, Django, Test Driven Development, Python Unit Testing, Angular JS, Selenium, REST, HTTP, FTP, JDBC, File, JMS, Flask, MVC, CSS Bootstrap, NGINX, CI/CD, Docker, AWS, MySQL, JIRA, MongoDB, MS SQL Server, T-SQL, Git, GitHub, Bootstrap, jQuery, Subversion, Stash/Git, Unit Testing, System Testing, Scipy, Pandas, Agile, Scrum, Continuous Integration, Integration Testing, Web Application Testing, PostgreSQL, Email, Messaging, Storage Services, Gerrit, Bash, Oracle DB, VMWare API, Amazon AWS, S3, SQS, Solr, RabbitMQ, webapp2, XML Schema, MS SQL Server 2012, Struts, JSP, Servlets, UNIX, SVN, ANT, XSLT, Object Modeling, Data Modeling, JSPs, JUnit, Oracle 10g, PHP, Web Server, HTTP 1.0, Socket, REST API, Graphical Passwords"
54931,54932,Python Developer,NaN,NaN,NaN,Python Developer at Intuit (08/2015 - Present); Python Developer at GE Energy (06/2014 - 07/2015); Python Developer at Safeway Inc (04/2013 - 05/2014); Python Developer at Intralinks Holdings Inc (11/2011 - 03/2013); Python Developer at Hexaware Technologies Limited (07/2010 - 10/2011); Software Developer at Vision InfoTech Pvt Ltd (03/2009 - 06/2010),NaN,"Python 3.1x, PyQuery, PyQt, Django, Angular.js, Open Stack, HTML, JavaScript, Node.js, DOM, JSON, MySQL, Git, Python Linux, Active Admin, Amazon Web Services, GitHub, Photoshop, Flash, Windows, Linux, Python 2.7, AWS, JSOM, REST, HTML5, CSS3, MVC, PHP, Flex, C++, XML, SOAP, Cassandra, UNIX, Python, Jenkins, agile, Java, XHTML, CSS, AJAX, Apache Web Server, Shell Scripting, SQL, PLSQL, Oracle"
54932,54933,Job Seeker,NaN,NaN,NaN,MetroBikes at MetroBikes (09/2018 - Present); Python/Flask Developer at TechJini Solutions Pvt. Ltd (04/2017 - 07/2018); Python Developer at TechJini Solutions Pvt. Ltd (12/2015 - 02/2017),NaN,"Analyzed and gathered business requirements, Developing mobile backend API's, Creating database schema, Deployed the project into AWS, Involved in Unit testing and Integration testing, Used JIRA for bug tracking and issue tracking, Used Amazon Elastic Beanstalk with Amazon EC2, Regular interaction with developers, Reporting Issues using Excel, Implementing controllers using flask frame work, Developing API's python/flask/mysql, Assisted engineering team, Worked with product management and business roles, Integrating modules and performing unit testing, Performed targeted user research, Developing Controllers using django framework, Designed APIs to retrieve the list of new tasks, Creating a Data models for the app, Developing the static pages using Bootstrap and CSS, Creating database schema for sqlite Database"

In [ ]:
master_df = master_df.merge(
    abilities_grouped,
    on="person_id",
    how="left"
)
master_df

,person_id,name,email,phone,linkedin,experience_text,education_info,skill,ability
0,1,Database Administrator,NaN,NaN,NaN,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017),"Bachelor of Science from Lead City University, Unknown Location (07/2013)","Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping","Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently."
1,2,Database Administrator,NaN,NaN,NaN,Database Administrator at Intercontinental Registry (12/2008 - 08/2011),"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)","sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel",database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements
2,3,Oracle Database Administrator,NaN,NaN,NaN,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016),"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)","DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)","Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)","Bachelor in Computer Science from University of Informatics, June 2007 (06/07)","Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS","SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office"
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013),"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)","Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD",Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication
...,...,...,...,...,...,...,...,...,...
54928,54929,Lead Python Developer,NaN,NaN,NaN,Lead Python Developer at People's United Bank (08/2016 - Present); Lead Python Developer at Entrust (10/2015 - 07/2016); Sr. Python Developer at Guide One Insurance (03/2014 - 09/2015); Sr. Python Developer at Examity (12/2012 - 02/2014); Python Developer at ANZ Bank (02/2011 - 09/2012); Web developer at Rofous (11/2007 - 01/2011),NaN,"Django, Angular JS, JavaScript, JQuery, Node.js, Python, Object Oriented Programming, Linux, JSON, REST, AWS, Ansible, MySQL, Oracle, PostgreSQL, SQLite3, C++, STL, BOOST, XML, XPath, XSLT, IBM MQ, Perl, Python Scripting, Apache2, Nginx, AJAX, Object Oriented Design, SDLC, Rational Rose, UML, PEP-8, PIP, SQL, MongoDB, STLC, Agile, Waterfall, Jenkins, Spark, Git, SVN, CAN, LIN, MOST, Sqoop, Hadoop, Flask, HTML5, CSS3, Matplotlib, Regular Expressions, Bootstrap, Natural Language Processing, Celery, RabbitMQ, VMWare, SOAP, Puppet, Elasticsearch, HTML, CSS, Numpy, Robot, GitHub, Bitbucket, Redis, Windows, Bash, AMQP, CRUD, Cassandra, JSF, Spring, Psutil, Sqlite3, Beautiful Soup, Vugen, SoapUI, PHP, PL/SQL, MS SQL Server, jQuery",Qualified Python Developer; Web Application Developer; Software Engineer; MVW frameworks; Mathematical operations; Object oriented programming; JSON based REST Web services; AWS; Ansible; SQL; Stored Procedures; Triggers; Cursors; Functions; MySQL; Oracle; PostgreSQL; SQLite3; Messaging system; C++; STL; BOOST; XML; XPath; XSLT; IBM MQ; Perl; Python scripting; Django; Angular JS; Java Script; JQuery; Node.js; Object Oriented Design; SDLC; Rational Rose; UML; PEP-8; PIP; SQL; PostgreSQL; Oracle; MongoDB; STLC; Agile; Waterfall; Jenkins; Spark; Git; SVN; CAN; LIN; MOST
54929,54930,Full Stack Python Developer,NaN,NaN,NaN,"Full Stack Python Developer at Fresenius Medical Care, MA (01/2016 - Present); Sr. Python Developer at Hughes Networks (03/2014 - 01/2016); Python Developer at Manheim Inc (05/2013 - 02/2014); Python Developer at DTCC (11/2012 - 05/2013); Java/ Python Developer at RBS India (01/2011 - 10/2012); Java Developer at Neon Infotech PVT LTD (08/2009 - 12/2010)",NaN,"Python, Django, AWS, AngularJS, Bootstrap, JavaScript, jQuery, JSON, HTML5, CSS3, MySQL, Linux, Ajax, Git, REST, XML, CSS, HTML, NodeJS, MongoDB, Cassandra, NumPy, Scipy, Jenkins, Ansible, Docker, AJAX, Backbone.js, D3.js, Java, JBoss, Node.js, Perforce, JIRA, J2EE, JSF, WebSphere, JPA, DHTML, JSP, Servlets, SQL, PL/SQL","Over 7 years of IT Experience; Designing, developing, testing and implementing various stand-alone and client-server architectures based enterprise application software; Developing web applications and implementing MVC architecture using Django web application frameworks; Agile Methodologies, Scrum stories and sprints experience in a Python based environment; Data analytics, data wrangling and Excel data extracts; Infrastructure Development and Operations involving AWS Cloud platforms; Project deployment using Jenkins and worked on Jenkins for continuous integration; Automating the process of launching and stopping/terminating EC2 instances on Amazon AWS; Using Python fabric for AWS instance provisioning; Build automation tools like Ant; Designing frontend layouts on the web using HTML5, CSS, JavaScript, jQuery and Bootstrap; MVC frameworks like AngularJS and jQuery; Analyzing and understanding complex systems, taking them apart and putting them back together again, only better, and with fewer lines of code; Object-Oriented design and coding, various Design Patterns and UML; Python packages like NumPy; Libraries such as UnitTest, JSON, CSV, and XML; Database optimization and developing stored procedures such as Triggers, Cursors, Joins, Views and SQL for various databases like MySQL, Oracle; Agile and Test Driven Development; SVN, Git, GITHUB, JIRA, CVS, Perforce, Jenkins; Various Python Integrated Development Environments like PyCharm, PyStudio, Sublime Text; Linux Bash shell scripting and following PEP Guidelines in Python; Designing REST/HTTP APIs, including JSON data formats and API versioning strategy; Developing Web Services (SOAP, RESTful) in Python using XML, JSON; Using Python HTTP APIs like Requests; Work experience for protocols in layer2 and up in the OSI stack including TCP/IP protocol stack, routing/switching algorithms; Implementing and working on the python code using shell scripting, troubleshooting, fixing and deploying many Python bug fixes; Various types of testing such as Unit testing, Integration testing, User acceptance testing and Functional testing; Open Stack APIs and Socket Programming; UNIX shell Scripts for automating batch programs; Programming and management in LINUX and UNIX environments"
54930,54931,Eli Lilly,NaN,NaN,NaN,Sr. Python Developer at Eli Lilly (08/2017 - Present); Sr. Python Developer at Comcast (01/2016 - 07/2017); Python Developer at Core logic (08/2013 - 12/2015); Python Developer at Concentrix Insurance Solutions (11/2011 - 07/2013); Java Developer at Solvent Software Solutions PVT LTD (09/2010 - 10/2011); Python Developer at Nova IT Solutions (07/2009 - 08/2010),NaN,"Python 2.7, HTML5, CSS3, AJAX, JSON, JQuery, Active Records, XML, SOAP, SOA, WSDL, Spring MVC, DTDs, XSD, Python APIs, Scala, Shell, Groovy, Perl, SQL, Shell Scripting, Jenkins, GIT, Heroku, Bugzilla, C++, Java, MS SQL, Visual Basic, Linux, Eclipse, JavaScript, JASPER, PL/SQL, Oracle 9i, HTML5/CSS, Apache, Python, HTML, CSS, Django, Test Driven Development, Python Unit Testing, Angular JS, Selenium, REST, HTTP, FTP, JDBC, File, JMS, Flask, MVC, CSS Bootstrap, NGINX, CI/CD, Docker, AWS, MySQL, JIRA, MongoDB, MS SQL Server, T-SQL, Git, GitHub, Bootstrap, jQuery, Subversion, Stash/Git, Unit Testing, System Testing, Scipy, Pandas, Agile, Scrum, Continuous Integration, Integration Testing, Web Application Testing, PostgreSQL, Email, Messaging, Storage Services, Gerrit, Bash, Oracle DB, VMWare API, Amazon AWS, S3, SQS, Solr, RabbitMQ, webapp2, XML Schema, MS SQL Server 2012, Struts, JSP, Servlets, UNIX, SVN, ANT, XSLT, Object Modeling, Data Modeling, JSPs, JUnit, Oracle 10g, PHP, Web Server, HTTP 1.0, Socket, REST API, Graphical Passwords","Developing and designing Web Based, Multi-tier distributed applications; Hands on experience working in WAMP and LAMP Architecture; Developing web-based applications using Python, Django, PHP, XML, CSS, HTML, Java Script and JQuery; Using Python's modules Numpy, matPlotLib, Pickle, PySide, Scipy, wxPython, PyTables for generating complex graphical data, creation of histograms; Writing and developing scripts for automating tasks using Jenkins and UNIX shell programming; Performing Unit testing, Integration Testing and generating of test cases for web applications using Junit and Python Unit test framework; Practicing the SDLC models, Agile methods with Scrum, Extreme Programming, Ticketing systems using JIRA and TDD; Developing Web Services with Python programming language; Using UNIX shell Scripts for automating batch programs; Developing complex SQL queries, Stored Procedures, Functions, Packages along with performing DDL and DML operations on the database; Using JSON based REST Web services and Amazon Web services; Writing Sub Queries, Stored Procedures, Triggers, Cursors and Functions on MySQL and PostgreSQL database; Using deployment tools like Heroku, Jenkins, pylint, cpp Check and Coverity; Working with GUI frameworks - PyJamas, Jython; Using NoSQL technologies like MongoDB, Cassandra and relational databases like Oracle, SQLite, PostgreSQL, Dynamo DB and MySQL databases; Performing code reviews and implementing best Pythonic programming practices; Writing test scripts, test cases, test specifications and test coverage; Handling errors/exceptions and debugging the issues in large scale applications"
54931,54932,Python Developer,NaN,NaN,NaN,Python Developer at Intuit (08/2015 - Present); Python Developer at GE Energy (06/2014 - 07/2015); Python Developer at Safeway Inc (04/2013 - 05/2014); Python Developer at Intralinks Holdings Inc (11/2011 - 03/2013); Python Developer at Hexaware Technologies Limited (07/2010 - 10/2011); Software Developer at Vision InfoTech Pvt Ltd (03/2009 - 06/2010),NaN,"Python 3.1x, PyQuery, PyQt, Django, Angular.js, Open Stack, HTML, JavaScript, Node.js, DOM, JSON, MySQL, Git, Python Linux, Active Admin, Amazon Web Services, GitHub, Photoshop, Flash, Windows, Linux, Python 2.7, AWS, JSOM, REST, HTML5, CSS3, MVC, PHP, Flex, C++, XML, SOAP, Cassandra, UNIX, Python, Jenkins, agile, Java, XHTML, CSS, AJAX, Apache Web Server, Shell Scripting, SQL, PLSQL, Oracle","Python Developer; Web/Application Developer; Analytical programming; Object Oriented Design and Programming; Web-based applications; Python best Practices (PEP-8); Python and Shell Scripting; Object oriented programming (OOP); WAMP and MVC Struts; Web Services; Front end development; Computer programming in R and Python; Application Servers; Web Servers; Integrated Development Environments; Web Services development; UNIX shell Scripts; Apache configuration; Version controls systems; SQL Queries, Stored procedures, functions, packages, tables, views and triggers; Requirements, architecture, test plans, design, quality analysis and audits; Windows, UNIX and Linux platforms"

In [ ]:
master_df.shape

(54933, 9)

In [ ]:
master_df.head()

,person_id,name,email,phone,linkedin,experience_text,education_info,skill,ability
0,1,Database Administrator,NaN,NaN,NaN,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017),"Bachelor of Science from Lead City University, Unknown Location (07/2013)","Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping","Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently."
1,2,Database Administrator,NaN,NaN,NaN,Database Administrator at Intercontinental Registry (12/2008 - 08/2011),"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)","sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel",database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements
2,3,Oracle Database Administrator,NaN,NaN,NaN,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016),"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)","DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)","Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",NaN,NaN,NaN,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)","Bachelor in Computer Science from University of Informatics, June 2007 (06/07)","Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS","SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office"
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013),"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)","Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD",Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication

In [ ]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54933 entries, 0 to 54932
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   person_id        54933 non-null  int64
 1   name             54819 non-null  object
 2   email            1593 non-null   object
 3   phone            1833 non-null   object
 4   linkedin         8538 non-null   object
 5   experience_text  54933 non-null  object
 6   education_info   48075 non-null  object
 7   skill            54858 non-null  object
 8   ability          54930 non-null  object
dtypes: int64(1), object(8)
memory usage: 3.8+ MB

In [ ]:
master_df[
    [
        "experience_text",
        "education_info",
        "skill",
        "ability"
    ]
].isnull().sum()

experience_text       0
education_info     6858
skill                75
ability               3
dtype: int64

In [ ]:
master_df = master_df.fillna("")

In [ ]:
master_df["resume_text"] = (
    master_df["name"] + " " +
    master_df["experience_text"] + " " +
    master_df["education_info"] + " " +
    master_df["skill"] + " " +
    master_df["ability"]
)

In [ ]:
master_df.head()

,person_id,name,email,phone,linkedin,experience_text,education_info,skill,ability,resume_text
0,1,Database Administrator,,,,Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017),"Bachelor of Science from Lead City University, Unknown Location (07/2013)","Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping","Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently.","Database Administrator Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017) Bachelor of Science from Lead City University, Unknown Location (07/2013) Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently."
1,2,Database Administrator,,,,Database Administrator at Intercontinental Registry (12/2008 - 08/2011),"bsc in computer science from lagos state university, Lagos, GU (Unknown Start)","sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel",database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements,"Database Administrator Database Administrator at Intercontinental Registry (12/2008 - 08/2011) bsc in computer science from lagos state university, Lagos, GU (Unknown Start) sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements"
2,3,Oracle Database Administrator,,,,Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016),"Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013)","DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years)","Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures","Oracle Database Administrator Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016) Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013) DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years) Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence",,,,"Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14)","Bachelor in Computer Science from University of Informatics, June 2007 (06/07)","Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS","SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office","Amazon Redshift Administrator and ETL Developer, Business Intelligence Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14) Bachelor in Computer Science from University of Informatics, June 2007 (06/07) Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office"
4,5,Scrum Master Scrum Master Scrum Master,,,,Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013),"Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013)","Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD",Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication,"Scrum Master Scrum Master Scrum Master Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013) Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013) Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication"

In [ ]:
print(master_df.loc[0, "resume_text"])

Database Administrator Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017) Bachelor of Science from Lead City University, Unknown Location (07/2013) Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently.

In [ ]:
master_df["resume_length"] = master_df["resume_text"].apply(
    lambda x: len(x.split())
)

In [ ]:
master_df["resume_length"]

0        240
1        176
2        285
3        405
4        156
        ...
54928    227
54929    411
54930    425
54931    192
54932    250
Name: resume_length, Length: 54933, dtype: int64

In [ ]:
master_df["resume_length"].describe()

count    54933.000000
mean       235.474141
std        181.565209
min         12.000000
25%        129.000000
50%        182.000000
75%        278.000000
max       2001.000000
Name: resume_length, dtype: float64

In [ ]:
master_df.sort_values(
    by="resume_length",
    ascending=False
)[["person_id", "resume_length"]].head()

       person_id  resume_length
34867      34868           2001
53178      53179           2001
16556      16557           2001
9442        9443           1901
46064      46065           1901

In [ ]:
print(master_df.loc[34867, "resume_text"])

Sr. Systems Engineer/ Administrator Sr. Systems Engineer/ Administrator at Squar Milner LLC (12/2016 - 07/2019); System/ Network Administrator at FSSI - Financial Statement Services Inc (05/2015 - 11/2016); System/ Network Administrator at Corinthian Colleges, Inc. / Everest College (10/2010 - 05/2015); System/ Network Administrator - Campus IT Support Professional at Career Institute (10/2007 - 10/2010); Lead IT Engineer/Corporate Technical Trainer at HP (04/1999 - 10/2008); Operations Manager, System/ Network Administrator at ProActive Business Solution (06/1995 - 04/1999) Diploma in Computer Networking and System Management from PCI College, Unknown Location (Unknown Start); Bachelor of Science in Electronic Engineering from Lee Ming Institute of Technology, Unknown Location (Unknown Start) Microsoft Active Directory administration/Group Policy Management, Microsoft Network Services including DHCP, DNS, Certificate Authority, DFS, Data Replications, Shared folders' NTFS Permissions, Microsoft Exchange (On-Prem Exchange 2016, Office 365 with Exchange online), ConnectWise ITIL ticketing system, Router/ Switch/Firewall/VPN installation, management and configuration, Umbrella/OpenDNS management and configuration, SAN/Cloud Storage solutions, VMWare and Hyper-V clustering virtualization technologies, Veeam backup, backup copy, replication solutions, Veeam One Suite monitoring, Carbon Black protection, Carbon Black Defense Anti-Virus software configuration and management, Barracuda email security appliance management and configuration, Servers/workstations system imaging deployment process including physical and virtual machines, Co-Locations/DataCenter support, equipment installation, configuration and management, Project management, new equipment planning and implementation, MSP/Vendors communication, Microsoft Active Directory Services/Group Policy/Data Replication, DFS, Data Replications, NTFS Permissions, Microsoft Exchange (Office 365 with Exchange online), Linux Server and host administration, Router/ Switch/Firewall/VPN management and configuration, NAS/SAN/Cloud Storage solutions, VMWare and Hyper-V virtualization technologies, Symantec Backup Exec solutions, Anti-Virus software configuration and management, Staff, Faculty Support & Student Support - all IT related issues, Infrastructure Management - Responsible for all IT equipment moves, add changes, Capacity - Responsible for maintaining accurate records regarding campus infrastructure capacity, Monitoring & Reporting - Responsible for delivery of Campus IT reporting to include both Admin and student network, Incident Management - Responsible for managing all service interruptions related to the delivery of IT functionality affecting the campus, Desktop Patch Management - Responsible for ensuring all desktops have all approved Microsoft (OS and Office) patches installed, Virus Management - Responsible for ensuring virus protection is in place and functioning across all PC devices in the campus environment, Curriculum Software - Responsible for installation and support of all curriculum software in use at the campus, Governance - Enforcing unauthorized usage of the system and making unauthorized copies of data, software, reports, and documents, Microsoft Active Directory Services/Group Policy/Replication, Microsoft Exchange Server administration, Managing and maintaining Active Directory Sties and Services, Domain Services, users/groups /roles/permissions, DHCP Server, DNS Server, Certificate Authority, Provide technical support for campus IT infrastructure. Install, configure and set-up Server, workstations, printers, telephones, fax machines and other network devices on-site, Support local area network technologies, to include wireless, switches and routers, Troubleshooting and resolving hardware and software issues for personal computers, printers and peripheral equipment, installing, diagnosing, maintaining, and upgrading PC hardware, printers and other equipment, Manage and maintain the incident/issue management queues for the Team & VOIP Telecom incidents or service requests to be ultimately resolved, Student virtualization lab support. Manage student and faculty computers by adding new computers to network, repairing and/or replacing hardware, repairing and/or reinstalling software, Responsible for analysis / troubleshooting, system monitoring, moves, adds changes, day to day maintenance and support of Cisco IP telephony communication systems when required, Administer and troubleshoot network and infrastructure issues related to the network. Assists in IT support functions and works with Technical Services staff, managing day to day operations of network. Responsible for incidents and requests, solve day to day tickets at campus, Technical liaison between campus administration and corporate IT teams. Adhere to and enforce corporate policies regarding network security, IT standards and corporate resources, Work with Corporate IT on projects and initiatives. Answer questions, trains and assists users on software packages used at campus. Responsible for coordination of manage service provider and vendor activities, Perform system refreshment for 4 Bank of America Banking Centers each week throughout Southern California, Leading a team of installation technicians performing all banking center computer equipment refreshment on Bank of America sites including Complete system backup, Server rack management, Network Router and switches, hubs, modems, UPS, cable panels, blade Server installation and configuration, Installing, diagnosing, maintaining, data migration and upgrading server hardware/OS, workstations, laptops hardware/OS, printers, scanners, and/or other equipment, Windows server 2003/2003R2/2008/2008R2 OS, Workstations Windows XP/7 OS implementation and configuration, providing on-site desktop and network support, banking center management and end-user support via phones and LAN remote management tools, Implementation of Network MFP printers with fax functionality, Network Dot Matrix check printers, QST, MICR, UPS and peripherals refreshment, perform Server, Workstations system upgrade, patches, installation and custom software package implementation, Communicating with HP control room to report and raise issues by utilizing HP ITIL Remedy system to log and track calls received as to nature of problem and how it was ultimately resolved, Banking center software installation and configuration including Merlin, Coin, and Banking center online and Microsoft office suites, Post installation equipment package deployment reporting and verification of all equipment functionality by banking center and Bank of America management. Perform hardware / software troubleshooting and maintenance activities on network Server, workstations, network printers, and other associated devices on sites, Leading installation team to perform Old 2U blade server, workstations and associated peripherals removal, repack, direct deployment packages to HP designated disposal center, Provide technical leadership and guidance to other field technicians. Ensure that the customer receives world class support and service, Provide support and train users as scheduled or when requested by the customer, Install, configure, and troubleshoot Server, desktop, laptops and associated peripherals for internal end- users, Install, configure and set-up Server, workstations, printers, telephones, fax machines and other network devices on-site, Support LAN/WAN technologies, to include wireless, switches and routers. Assists in general IT support functions and works with Technical Services staff, managing day to day operations of network. Responsible for incidents and requests, solve day to day tickets to report how it was resolved, High level of proficiency in computer skills with a passion for technology. A commitment to continuing education to strengthen skills and broaden expertise. Strong problem solving and troubleshooting capabilities. Ability to learn new skills quickly with minimal guidance. Dedicated to achieving project schedules and milestones, Coordinated and accomplished computer hardware, system and network configuration, e-commerce with shopping cart environment, implemented new sales and marketing strategies to initiate company website including electronic catalog for more than 15,000 items, online shopping and ordering system with 25% increase in sales within 6 months, Communicated and negotiated with vendors and service provider for more than 15,000 products, implemented new purchasing policy with cost effective buying strategies among vendors, Reorganized warehouse operations; implemented new services, procedures and policies, resulting in improved delivery of quality products and services, staff scheduling while significantly reducing 20% of operating expenses annually Microsoft Active Directory administration/Group Policy Management; Microsoft Network Services including DHCP, DNS, Certificate Authority; DFS, Data Replications, Shared folders' NTFS Permissions; Microsoft Exchange (On-Prem Exchange 2016, Office 365 with Exchange online); ConnectWise ITIL ticketing system; Router/ Switch/Firewall/VPN installation, management and configuration; Umbrella/OpenDNS management and configuration; SAN/Cloud Storage solutions; VMWare and Hyper-V clustering virtualization technologies; Veeam backup, backup copy, replication solutions, Veeam One Suite monitoring; Carbon Black protection, Carbon Black Defense Anti-Virus software configuration and management; Barracuda email security appliance management and configuration; Servers/workstations system imaging deployment process including physical and virtual machines; Co-Locations/DataCenter support, equipment installation, configuration and management; Project management, new equipment planning and implementation, MSP/Vendors communication; Linux Server and host administration; Symantec Backup Exec solutions; Anti-Virus software configuration and management; Staff, Faculty Support & Student Support - all IT related issues; Infrastructure Management - Responsible for all IT equipment moves, add changes; Capacity - Responsible for maintaining accurate records regarding campus infrastructure capacity; Monitoring & Reporting - Responsible for delivery of Campus IT reporting to include both Admin and student network; Incident Management - Responsible for managing all service interruptions related to the delivery of IT functionality affecting the campus; Desktop Patch Management - Responsible for ensuring all desktops have all approved Microsoft (OS and Office) patches installed; Virus Management - Responsible for ensuring virus protection is in place and functioning across all PC devices in the campus environment; Curriculum Software - Responsible for installation and support of all curriculum software in use at the campus; Governance - Enforcing unauthorized usage of the system and making unauthorized copies of data, software, reports, and documents; Student virtualization lab support. Manage student and faculty computers by adding new computers to network, repairing and/or replacing hardware, repairing and/or reinstalling software; Responsible for analysis / troubleshooting, system monitoring, moves, adds changes, day to day maintenance and support of Cisco IP telephony communication systems when required; Technical liaison between campus administration and corporate IT teams. Adhere to and enforce corporate policies regarding network security, IT standards and corporate resources; Work with Corporate IT on projects and initiatives. Answer questions, trains and assists users on software packages used at campus. Responsible for coordination of manage service provider and vendor activities; Perform system refreshment for 4 Bank of America Banking Centers each week throughout Southern California; Leading a team of installation technicians performing all banking center computer equipment refreshment on Bank of America sites including Complete system backup, Server rack management, Network Router and switches, hubs, modems, UPS, cable panels, blade Server installation and configuration; Installing, diagnosing, maintaining, data migration and upgrading server hardware/OS, workstations, laptops hardware/OS, printers, scanners, and/or other equipment; Windows server 2003/2003R2/2008/2008R2 OS, Workstations Windows XP/7 OS implementation and configuration, providing on-site desktop and network support, banking center management and end-user support via phones and LAN remote management tools; Implementation of Network MFP printers with fax functionality, Network Dot Matrix check printers, QST, MICR, UPS and peripherals refreshment, perform Server, Workstations system upgrade, patches, installation and custom software package implementation; Communicating with HP control room to report and raise issues by utilizing HP ITIL Remedy system to log and track calls received as to nature of problem and how it was ultimately resolved; Banking center software installation and configuration including Merlin, Coin, and Banking center online and Microsoft office suites; Post installation equipment package deployment reporting and verification of all equipment functionality by banking center and Bank of America management. Perform hardware / software troubleshooting and maintenance activities on network Server, workstations, network printers, and other associated devices on sites; Leading installation team to perform Old 2U blade server, workstations and associated peripherals removal, repack, direct deployment packages to HP designated disposal center; Provide technical leadership and guidance to other field technicians. Ensure that the customer receives world class support and service; Provide support and train users as scheduled or when requested by the customer; Install, configure, and troubleshoot Server, desktop, laptops and associated peripherals for internal end- users; Install, configure and set-up Server, workstations, printers, telephones, fax machines and other network devices on-site; Support LAN/WAN technologies, to include wireless, switches and routers. Assists in general IT support functions and works with Technical Services staff, managing day to day operations of network. Responsible for incidents and requests, solve day to day tickets to report how it was resolved; High level of proficiency in computer skills with a passion for technology. A commitment to continuing education to strengthen skills and broaden expertise. Strong problem solving and troubleshooting capabilities. Ability to learn new skills quickly with minimal guidance. Dedicated to achieving project schedules and milestones; Coordinated and accomplished computer hardware, system and network configuration, e-commerce with shopping cart environment, implemented new sales and marketing strategies to initiate company website including electronic catalog for more than 15,000 items, online shopping and ordering system with 25% increase in sales within 6 months; Communicated and negotiated with vendors and service provider for more than 15,000 products, implemented new purchasing policy with cost effective buying strategies among vendors; Reorganized warehouse operations; implemented new services, procedures and policies, resulting in improved delivery of quality products and services, staff scheduling while significantly reducing 20% of operating expenses annually

In [ ]:
master_df["resume_text"].duplicated().sum()

np.int64(36639)

In [ ]:
master_df[master_df["resume_text"].duplicated(keep=False)][
    ["person_id", "name", "resume_text"]
].head(10)

,person_id,name,resume_text
0,1,Database Administrator,"Database Administrator Database Administrator at Family Private Care LLC (04/2017 - Present); Database Administrator at Incomm (01/2014 - 02/2017) Bachelor of Science from Lead City University, Unknown Location (07/2013) Database administration, Database, Ms sql server, Ms sql server 2005, Sql server, Sql server 2005, Sql server 2008, Sql server 2008 r2, Sql server 2012, Sql, Sql queries, Stored procedures, Clustering, Backups, T-sql, Virtualization, R2, Maintenance, Problem solving, Shipping Installation and Building Server; Running Backups; Recovering and Restoring Models; Support various MS SQL Server; MS SQL Server 2005/2008; environments from SQL Server; /2008R2R2/2012/2014; 2005 thru SQL Server 2008r2 as; administration including; well as with SQL Server 2012 on; installation, configuration,; upgrades, capacity planning,; performance tuning, backup and; recovery.; Familiar with virtualization and; managing SQL databases in a; virtual environment.; Management of users including; creation/alteration, grant of; system/DB roles and permissions; on various database objects.; Design and implement SQL Server; 201, databases for mission-critical; 2005, SQL Server 2008 R2,; business.; Environment transition planning; (development, test, stage,; production).; Perform routine backup and; recovery testing and documenting; recovery scenarios.; Use SQL Profiler for; troubleshooting, monitoring, and; optimization of SQL Server and; SQL code.; Manage the production and; development databases including; performance tuning, capacity; planning, SQL Server clustering,; database security configuration,; and database continuity.; Excellent analytical,; communication skills, work ethics; and ability to work in a team; environment with strong; determination and commitment to; the deliverables.; Highly motivated self-starter with; the ability to work independently."
1,2,Database Administrator,"Database Administrator Database Administrator at Intercontinental Registry (12/2008 - 08/2011) bsc in computer science from lagos state university, Lagos, GU (Unknown Start) sql server management studio, visual studio, sql, microsoft powerpoint, windows xp, microsoft office, assembly language, microsoft windows 7, c, c#, visual basic, java programming, microprocessors, hardware/systems design, digital electronics, system organization, microsoft excel database management systems administration; developing and maintaining database; working on high-end servers; analyzing business requirements; developing and designing data models; providing and designing db tools; assessing and executing implementing of new technologies; working in coordination with company developers and project managers; developing training programs; training technical support and applications personnel; monitoring performance and capacity; providing resolutions to system problems; providing technical support for sql database environment; overseeing databases development and organization; communicating regularly with staff; creating database with back-up system; monitoring data availability for faster query response; designing conceptual schema as per the client needs; looking after the security of company data; testing and installing latest versions of database management systems; granting access to users as per their needs and requirements"
2,3,Oracle Database Administrator,"Oracle Database Administrator Oracle Database Administrator at Cognizant (06/2016 - Present); Oracle Database Administrator at Convergys (06/2014 - 06/2016) Master of Computer Applications in Science and technology from JNTU - Kakinada, Andhra Pradesh, Kakinada, Andhra Pradesh (2013) DATABASES, ORACLE (4 years), ORACLE 10G, SQL, LINUX, RMAN (4 years), DATAGUARD (3 years) Over 4+ years of Experience as Architecture; Experienced in Installation and Maintaining Highly Critical Databases in any Operational mode on Unix/Linux, Sun Solaris; Experienced in 10g, 11g, 12c databases; Responsible for installing Oracle 11g and 12c in Single Node & Multi node's Configure host and listener; Experienced in Creating Users, Roles and Profiles, Assigning Roles and Profiles to Users; Experience on Data Guard setup 10g/11g/12c; Expertise in Managing and monitoring Database Storage Structures, Data Files Space, Resizing and Adding new Data files; Maintaining the Cold and Hot, Logical and RMAN Backups of the Databases; Performing Logical Backups Using Export Utility and Restoring Specific Object or Schema Using Import Utility; Monitoring and Performing Daily incremental Backups, Weekly Backups Using RMAN; Experience in Concept of Flashback Mechanism; Having Good and Usable Knowledge on Automatic Storage Management(ASM), Conversion of Non-ASM Database to ASM Database and Monitoring ASM instances; Experience on Cloning User man and RMAN; Experience on Applying patches to Database CPU and PSU and interim Patches; Experience on Performance tuning and Troubleshooting of Database; Maintaining of Buffer Cache, Library Cache, and Dictionary Cache; Taking Care of Wait Events, Analysing Instance and System Performance; Analysing the DB performance Using AWR, ASH and ADDM Reports; Upgrade Database from 10g to 11g and 11g to 12c; Creation of ASM Databases, ASM Instances; Backups & Recovery of Databases, Table-Spaces, Data files, Design and Develop Database Backup, Recovery and Operations Procedures"
3,4,"Amazon Redshift Administrator and ETL Developer, Business Intelligence","Amazon Redshift Administrator and ETL Developer, Business Intelligence Amazon Redshift Administrator and ETL Developer, Business Intelligence at MSP Recovery - Fort Lauderdale, FL (02/18 - Present); Database Administrator at CEAACES - Quito, Provincia de Pichincha (11/14 - 12/15); Database Administrator at Ceige - Havana, IL (09/07 - 10/14) Bachelor in Computer Science from University of Informatics, June 2007 (06/07) Maintain multiple database environments (Redshift, RDS) in AWS, User management and group in Redshift, Design and Developed ETL jobs to extract data from RDS and load it in Redshift Matillion ETL and python script, Experience working within the AWS Big Data Ecosystem (S3, RDS, and Redshift), Expertise in development of various reports and prepare the data for the utilization with tableau, Expertise Query Tuning and Performance optimization and Implementing Work Load management, Managing Amazon Redshift Snapshots using the console, Designed of Conceptual Logical Model and Physical Model, Implemented, supported and managed the database, Kept data integrity and availability, Designed, deployed and monitored database servers, Managed user administration, Migrated different databases in SQL Management, PostgreSQL and Oracle, Migrated and created new database structures, such as tables, indexes and stored procedures from development to the production environment, Created and tuned query, stored procedures, triggers, views and added/changed tables for data load and transformation, and data extraction, Created backup and restored strategy of production, development and test environments, Executed recovery databases and created the documentation to provide the disaster recovery processes, Produced entity relationship & data flow diagrams, database normalization schemata logical to physical database maps, and data table parameters, Installed and managed Database Server, Created and monitored user accounts, user permissions, database extents and table partitions, Implemented robust backup and recovery procedures based on data volatility and application availability requirements, Monitored and optimized system performance using index tuning, disk optimization, and other methods, Monitored the size of the transaction log. Managed databases on multiple disks using Disk Mirroring technology, Collected, stored, managed, and enabled the ability to query the organization's metadata, Ensured data availability using administration tactics, Designed, debugged, implemented, and maintained stored procedures, triggers, and user-defined functions that are stored in the DBMS SQL management; PostgresSQL; Oracle; MySQL; microsoft office; PHP; .NET; ETL; Data Warehouse; Datastage; Data Stage; Data modeling and database design; Metadata management and repository usage; Manage large databases; Backup and recovery procedures; Solve technical problems; Good communication skills; Procedural skills; Focus on deadlines and deliverables; Work with SQL Management, PostgreSQL, Oracle, MySQL, Microsoft Office"
4,5,Scrum Master Scrum Master Scrum Master,"Scrum Master Scrum Master Scrum Master Scrum Master at Quest Technologies (10/2015 - 04/2019); Oracle Database Administrator/ Scrum Master at Prudential (06/2013 - 10/2015); Junior Oracle Database Administrator at Time Warner Cable (05/2012 - 06/2013) Unknown Program from Virginia Commomwealth University, Richmond, VA (08/2013) Scrum, Agile software development, Product backlog grooming, Burnup and burndown charts, Dependency management, Problem solving, Continuous improvement, Production support, Agile process, Sprint planning, Backlog grooming, Retrospective meetings, Oracle 10g and 11g administration, RMAN backups, Security patching, Performance tuning, ASM configuration, Auditing, Database monitoring, Grid-based monitoring, Data Guard configuration, Oracle Streams, Materialized views, Oracle Enterprise Manager, Oracle RAC maintenance, Data replication, TOAD Scrum Master; Agile software development; Product backlog management; Metrics and status tracking; Dependency management; Problem solving; Continuous improvement; Production support; Oracle database administration; RMAN backups; Security patching; Performance tuning; ASM configuration; Auditing; Database monitoring; Grid-based monitoring; Data Guard configuration; Oracle Streams; Materialized views; Oracle Enterprise Manager; Oracle RAC maintenance; Data replication"
5,6,Oracle Database Administrator,"Oracle Database Administrator Oracle Database Administrator at SUNTRUST BANK (02/2015 - Present); Oracle Database Administrator at ESTES-EXPRESS (03/2013 - 02/2015); Field Service Representative / Technician at ROCHE DIAGNOSTICS FOR ADECCO TECHNICAL (10/2009 - 03/2013) Unknown Program from School of Professional and Graduate Studies/Technical Courses, BAKER UNIVERSITY, Overland Park, KS (Unknown Start); General/Business/Science Courses from UNIVERSITY OF ALASKA, Anchorage, AK (Unknown Start) Oracle Databases, Database Administration, Database Monitoring, Database Tuning, Database Backup and Recovery, Database Cloning, Database Patching, Database Upgrades, Database Migration, Database Security, SQL Tuning, PL/SQL, Shell Scripting, RMAN, Data Guard, RAC, ASM, GoldenGate, Enterprise Manager, Flashback Technology, Performance Monitoring and Tuning, SQL Tuning Tools, Data Pump, Transportable Tablespaces, Materialized Views, Replication, Oracle Database Administration, Streams, Physical Standby Databases, Technical Support, Equipment Installation, Equipment Maintenance, Software Updates, Electrical Safety Testing, Data Entry, Microsoft Excel Oracle Database Administration; Database Backup and Recovery; Database Tuning and Optimization; Database Cloning and Migration; Database Patching and Upgrades; Database Security Management; SQL Tuning; PL/SQL Development; Shell Scripting; RMAN; Data Guard; RAC; ASM; GoldenGate; Enterprise Manager; Flashback Technology; Performance Monitoring and Tuning; SQL Tuning Tools; Data Pump; Transportable Tablespaces; Materialized Views; Replication; Technical Support; Equipment Installation and Maintenance; Software Updates; Electrical Safety Testing; Data Entry; Microsoft Excel"
6,7,Oracle Database Administrator,"Oracle Database Administrator Oracle Database Administrator at Caresource (06/17 - Present); Oracle Database Administrator at Anthem (04/16 - 06/17); Production Support Database Administrator at PNC Bank (03/13 - 04/16) Biochemistry from University Of Yaounde, Yaounde (04/08) Oracle Database, Oracle Database Administration, Oracle Exadata, Oracle Enterprise Manager Cloud Control 12c & 13c, Oracle 11gR2 RAC, Linux, Solaris, Installation, Upgrading, Patching, Sizing, Oracle Databases, Oracle Database Objects, Data Migrations, Troubleshooting, Performance & Tuning, Backup & Recovery, Database Integrity, Security, TDE, Transparent Data Encryption, SQA, Software Quality Assurance, Requirement Gathering, Test Cases Development, Oracle EBS, Oracle 9i, Oracle 10g, Oracle 11g, Oracle 12c RAC, Oracle Clusterware, ASM, Grid Installation, RAC Clusterware Administration, Configuration, SRVCTL, CRSCTL, ASMCMD, CELLCLI, DCLI, RMAN, Recovery Manager, PITR, TSPITR, Export/Import, Flashback Technologies, Disaster Recovery, Archival Processing, Data Protection, Performance Tuning, EXPLAIN PLAN, TKPROF, STATSPACK, SQL TRACE, ORADEBUG, SQL Coding, DDL, DML, V$ Performance Views, SQL Tuning Advisor, SQL Profiles, SQL Monitoring, SQL Access Advisor, SQL Baselines, SQLTXTRACT, Critical Patch Update, Patch Set Update, One-off Patches, OPatch, Logical Data Model, Physical Data Model, ERwin Modeler, Flashback Recovery, Data Pump, AWR, ADDM, ASH, Recycle Bin, Grid Monitoring, Cross Platform Migrations, Windows, HP, AIX, Oracle Dataguard, Physical Standby Databases, Shell Scripts, ASM File System Migration, RMAN Catalog, RMAN No Catalog, Point-In-Time Recovery, Flashback, Cross Platform Transportable Tablespace, Statspack, Explain Plan, Upgrades, Patches, TAR Support, Cloning, Backups, Capacity Planning, Documentation, Exadata, Red Hat Linux 6.5, Datapump, EXPDP, IMPDP, RMAN Duplicate, Database Cloning, Backup/Restoration Strategy, Logical Backups, Export/Import Data Pump, Oracle Enterprise Manager 12c, Oracle Management Repository, EMCTL, Incident Rules, Administration Groups, Template Collections, SQL Tuning, PL/SQL Tuning, Oracle Contention, Secure SCP, Secure FTP, SQL Trace, 2 Node RAC, Linux 11g R2, Dataguard, Logical Standby, Physical Standby, Datapump Export/Import, Recovery Strategies, Database Crash Recovery, Media/Disk Failure Recovery, Physical Backups, CRON, Oracle 12C RAC, Golden Gate, CRS, User Management, Groups, Roles, Profiles, Privileges, Integrity Constraints, Database Triggers, Security Patches, Patch Set, Critical Patch Updates, Patch Set Updates, One-off Patch, Transportable Tablespace, Data Refreshes, Oracle 10gR2 RAC, Oracle 12c, Oracle Wallet, Tablespace TDE, V$ Dynamic Performance Views, Alert Log Files, Trace Files, Space Management, Database Maintenance, Failover, Switchover, Data Guard Broker, Materialized Views, Oracle Streams, Oracle 10gR2 Patches Oracle Database Administration; Oracle Exadata; Oracle Enterprise Manager; Oracle RAC; Linux Administration; Solaris Administration; Database Installation; Database Upgrading; Database Patching; Database Sizing; Database Objects Management; Data Migrations; Database Troubleshooting; Database Performance Tuning; Database Backup and Recovery; Database Integrity and Security; Transparent Data Encryption; Software Quality Assurance; Requirement Gathering; Test Cases Development; Oracle EBS Administration; Oracle Clusterware Administration; ASM Administration; Grid Infrastructure Installation; RMAN Administration; Disaster Recovery Planning; Archival Processing; Data Protection; SQL Tuning; Database Patching; Logical and Physical Data Modeling; Database Migration and Upgrades; Oracle Dataguard Administration; Cross Platform Database Migrations; Database Cloning and Refreshes; Database Performance Monitoring and Tuning; Database Maintenance and Documentation"
7,8,Lead Database Administrator/Developer,"Lead Database Administrator/Developer Lead Database Administrator/Developer at Department of Housing and Urban Development (2017 - Present); Production Support Database Administrator at Citi Group (2016 - 2017); Oracle Database Administrator at Citi Group (2014 - 2015); Database Administrator at University of Maryland, University College (2012 - 2014) Bachelor's Degree in BiologyChem / Computer Science from Bowie State University, Unknown Location (Unknown Start) Databases, Database Administration, Database Development, DBA, ETL, Oracle Dba, Sql Dba, Sql Server, Ssis Collaborate with a team of diverse and multifaceted database administrators; Effectively gather requirements for business and technical design, development, and testing implementation; Successfully perform database monitoring and tuning; Ensure proper operational activities including backups and restores, troubleshooting of applications, and moves, adds, and changes; Audit, modify, and amend data in systems utilizing SQL commands, bulk import, and manual-editing; Organize logistics with regard to database changes necessary for data conversion, tool configuration, data refresh migration, and other initiatives for large application development projects; Configure, manage & upgraded Windows Servers 2008 R2, 2012 R2 and 2016 specifically as it relates to MS SQL Server installations and mission critical systems; Organized a successful transition from legacy system to new Cloud systems with minimal disruption to the business; Eliminated months of production server issues by systematically troubleshooting and resolving the problem with no further downtime; Reduced the deployment downtown by recommending incremental backup procedures in order to expedite Production code deploys; Improved the release process by implementing and adapting the Agile software development methodology; Effectively oversaw a team of six production support analysts, developers and administrators; Managed production, processes, and job amends and corrections to ensure all SLAs were met; Successfully identified processing deficiencies while driving automation techniques effectively increasing workflow efficiency and maximizing operations; Collaborated directly with a diverse and multifaceted team to ensure minimal downtime of implemented systems with full responsibility for 24/7 application support; Reduced bill cycle turnaround time by one day for billing department while creating statistical scorecards for bill cycle run times; Improved vital processing jobs by reducing process duration by 60%; Managed core database administration activities enterprise-wide including Oracle database configuration, and infrastructure; Successfully administered policy and best practices for all database systems including logical and physical designs, maintenance, backup, and recovery; Effectively drove day to day and routine support, troubleshooting of issues, and backup and recovery; Created and managed roles and profiles including granting, revoking, and updating user access to Oracle databases; Collaborated with a team of six database administrators in an effort to drive daily operational support including database installation, management, and daily support activities; Oversaw management for database design, structure, data integrity, and delivery of data services for multiple systems; Implemented improvements in data management for the IT department ensuring compliance of database policies and procedures; Analyzed database security audit reporting for database access and SOX compliance; Created indexes ensuring optimum database performance and data loading to better manage disk space and optimized disk I/O; Completed database restores and recovery operations including database refreshes of production data to better test and develop databases to ensure all are in sync after restoration"

In [ ]:
master_df["person_id"].duplicated().sum()

np.int64(0)

In [ ]:
master_df["name"].duplicated().sum()

np.int64(44403)

In [ ]:
dup_text = master_df["resume_text"][
    master_df["resume_text"].duplicated()
].iloc[0]

master_df[master_df["resume_text"] == dup_text][
    ["person_id", "name", "resume_text"]
]

,person_id,name,resume_text
1736,1737,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"
2115,2116,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"
20047,20048,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"
20426,20427,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"
38358,38359,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"
38737,38738,MIS Director/Homeless Management Information Systems Database Administrator,"MIS Director/Homeless Management Information Systems Database Administrator MIS Director/Homeless Management Information Systems Database Administrator at Community Alliance for the Homeless, Inc (03/2010 - Present); Network Administrator at CVM - Memphis, TN (08/1999 - 02/2010); MIS Site Manager at Bally's Saloon & Gambling Hall (05/1995 - 07/1999) Computer Science in Business from Memphis School for the Deaf, Unknown Location (Unknown Start); Unknown Program from Southeast College of Technology, Unknown Location (Unknown Start) Database Administration, Database Security, Assessment Building, Regulatory Adherence to Policy & Procedures, Team & Project Leadership, Contingency Planning, Budgeting, Contract Negotiations, Staff Management, Data Quality & Integrity, Monitored all operations of Information Systems, Planning, Purchasing, Troubleshooting, Y2K Project Team Leader, Setups of new installations, Supervised 12 Computer Operators, Scheduling, Tracking attendance, Training of hardware and software, Oversaw system maintenance, Monitored system status of hardware on property, Tracked and prepared a periodic inventory of all hardware and software, Prepared marketing extract as approved by the MIS Manager, Loaded and monitored all PTF's and Versions on the computer system, Trained and aided users on computer system, Maintained job logs and problem logs, Prepared and maintained documentation, Ensured distributions of information as required for upgrades, Ensured timely distribution of reports, Performed preventive maintenance and inventory functions Database Administration; Database Security; Assessment Building; Regulatory Adherence to Policy & Procedures; Team & Project Leadership; Contingency Planning; Budgeting; Contract Negotiations; Staff Management; Data Quality & Integrity; Monitored all operations of Information Systems; Planning; Purchasing; Troubleshooting; Y2K Project Team Leader; Setups of new installations; Supervised 12 Computer Operators; Scheduling; Tracking attendance; Training of hardware and software; Oversaw system maintenance; Monitored system status of hardware on property; Tracked and prepared a periodic inventory of all hardware and software; Prepared marketing extract as approved by the MIS Manager; Loaded and monitored all PTF's and Versions on the computer system; Trained and aided users on computer system; Maintained job logs and problem logs; Prepared and maintained documentation; Ensured distributions of information as required for upgrades; Ensured timely distribution of reports; Performed preventive maintenance and inventory functions"

In [ ]:
## Duplicate Resume Analysis

# - Total candidates: 54,933
# - Duplicate person_id: 0
# - Duplicate resume_text: 36,639

# Observation:
# The dataset contains many identical resumes with different person_ids.
# This appears to be a characteristic of the source dataset rather than an issue in preprocessing.

# Decision:
# Do not remove duplicates during EDA.
# Duplicates will be removed later when creating the training dataset.

In [ ]:
master_df.shape

(54933, 11)

In [ ]:
master_df.columns

Index(['person_id', 'name', 'email', 'phone', 'linkedin', 'experience_text',
       'education_info', 'skill', 'ability', 'resume_text', 'resume_length'],
      dtype='object')

In [ ]:
master_df.isnull().sum()

person_id          0
name               0
email              0
phone              0
linkedin           0
experience_text    0
education_info     0
skill              0
ability            0
resume_text        0
resume_length      0
dtype: int64